export enum Keyword {
  ACCELERATE = 'accelerate',
  ACTION = 'action',
  AMBUSH = 'ambush',
  ASSAULT = 'assault',
  BACKLINE = 'backline',
  DEATHKNELL = 'deathknell',
  DEFLECT = 'deflect',
  EQUIP = 'equip',
  GANKING = 'ganking',
  HIDDEN = 'hidden',
  HUNT = 'hunt',
  LEGION = 'legion',
  LEVEL = 'level',
  QUICK_DRAW = 'quick_draw',
  REACTION = 'reaction',
  REPEAT = 'repeat',
  SHIELD = 'shield',
  TANK = 'tank',
  TEMPORARY = 'temporary',
  UNIQUE = 'unique',
  VISION = 'vision',
  WEAPONMASTER = 'weaponmaster',
}